server.port = 8080

spring.security.user.name= hello
spring.security.user.password=hello_world

########################  ORACLE DB #######################################
spring.datasource.url=jdbc:oracle:thin:@10.201.60.22:1521/MED
spring.datasource.username=eclinic
spring.datasource.password=Kng2023
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.jpa.properties.hibernate.default_schema=ECLINIC
spring.jpa.show-sql=false
spring.jpa.database-platform=org.hibernate.dialect.Oracle12cDialect

#logging.level.org.hibernate.type.descriptor.sql=trace

spring.thymeleaf.cache=false
spring.thymeleaf.mode=LEGACYHTML5


############################################################################