SELECT 
PRIMARY_ID,
CIVIL_ID_NO,
MILITARY_NO,
NAME_E,
NAME_A,
GENDER,
DOB,
MOBILE_NO,
DESIGNATION,
NATIONALITY,
JOB_STATUS,	
RELATION 
FROM NUTRIO.NUTRIO_VW_HR_FAMILY 
where MILITARY_NO = :militaryId
--where MILITARY_NO = 1914
FETCH FIRST 1 ROW ONLY