SELECT 
nr.OP_NUMBER AS MEDICAL_RECORD_NO,
nr.PATIENT_NAME AS PATIENT_NAME_EN,
nr.PATIENTNAME_AR AS PATIENT_NAME_AR,
nr.MOBILE AS MOBILE_NO,
CAST(nr.EMPLOYEE_ID AS NUMBER(12,0)) AS MILITARY_NO,
CAST(nr.EMIRATES_ID  AS NUMBER(12,0)) AS PAT_CIVIL_ID_NO,
CAST(nr.EMP_CIVIL_ID  AS NUMBER(12,0)) AS EMP_CIVIL_ID_NO,
nr.SEX AS GENDER,
nr.RELATIONSHIP AS RELATIONSHIP,
nr.DESIGNATION,
CASE WHEN nr.RELATIONSHIP IS NULL OR nr.RELATIONSHIP IN ('KNG Officer') THEN 1
	 WHEN nr.RELATIONSHIP IN ('Father') THEN 2
	 WHEN nr.RELATIONSHIP IN ('Son') THEN 3 
	 WHEN nr.RELATIONSHIP IN ('Daughter') THEN 4
	 WHEN nr.RELATIONSHIP IN ('Mother') THEN 5
	 WHEN nr.RELATIONSHIP IN ('Wife') THEN 6
 END AS ORDER_NO,
nr.PAT_TYPE,
nr.DATE_OF_BIRTH AS BIRTH_DATE
FROM medas.NEW_REGISTRATION nr 
--WHERE nr.OP_NUMBER IN ('KNG-06-000394')
WHERE nr.OP_NUMBER IN (:opNum)
AND REGEXP_LIKE(nr.EMPLOYEE_ID, '^[0-9]+$') 
AND REGEXP_LIKE(nr.EMIRATES_ID, '^[0-9]+$')