SELECT 
'' AS MEDICAL_RECORD_NO,
v.NAME_E AS PATIENT_NAME_EN,
v.NAME_A AS PATIENT_NAME_AR,
v.MOBILE_NO,
v.MILITARY_NO AS MILITARY_NO,
v.CIVIL_ID_NO AS PAT_CIVIL_ID_NO,
v.PRIMARY_ID AS EMP_CIVIL_ID_NO,
v.GENDER,
v.RELATION AS RELATIONSHIP,
v.DESIGNATION,
CASE 
		WHEN v.JOB_STATUS LIKE 'Working' AND v.MILITARY_NO  < 3000 AND v.RELATION IN ('KNG Officer') THEN 'Officer'
		WHEN v.JOB_STATUS LIKE 'Working' AND v.MILITARY_NO > 3000 AND v.MILITARY_NO <50000 AND v.RELATION IN ('KNG Officer') THEN 'Soldiers'
		WHEN v.JOB_STATUS LIKE 'Family' AND v.RELATION IN ('Father') THEN 'Father'
		WHEN v.JOB_STATUS LIKE 'Family' AND v.RELATION IN ('child') AND v.GENDER IN ('Male') THEN 'Son'
		WHEN v.JOB_STATUS LIKE 'Working' AND v.MILITARY_NO > 50000 THEN 'Professionals' 
		WHEN v.JOB_STATUS LIKE 'Not Working' THEN 'Retired'
END AS PAT_TYPE,
v.DOB as BIRTH_DATE
FROM MEDAS.VW_HR_FAMILY v
WHERE v.CIVIL_ID_NO IN (:civilId)