SELECT 
a.MEDICAL_RECORD_NO,
a.PATIENT_NAME_EN, --CL_VL
a.PATIENT_NAME_AR, --CL_VL
a.MOBILE_NO, --CL_VL
a.MILITARY_NO, --CL_VL
a.PAT_CIVIL_ID_NO, --CL_VL
a.EMP_CIVIL_ID_NO,
a.RELATIONSHIP,
a.GENDER, --CL_VL
a.DESIGNATION, --CL_VL
a.PAT_TYPE  --CL_VL
FROM 
(
-- --------------------------------------------------------------------
	(
	SELECT 
	nr.OP_NUMBER AS MEDICAL_RECORD_NO,
	nr.PATIENT_NAME AS PATIENT_NAME_EN,
	nr.PATIENTNAME_AR AS PATIENT_NAME_AR,
	nr.MOBILE AS MOBILE_NO,
	CAST(nr.EMPLOYEE_ID AS NUMBER(12,0)) AS MILITARY_NO,
	CAST(nr.EMIRATES_ID  AS NUMBER(12,0)) AS PAT_CIVIL_ID_NO,
	CAST(nr.EMP_CIVIL_ID  AS NUMBER(12,0)) AS EMP_CIVIL_ID_NO,
	nr.SEX AS GENDER,
	nr.RELATIONSHIP AS RELATIONSHIP,
	nr.DESIGNATION,
	CASE WHEN nr.RELATIONSHIP IS NULL OR nr.RELATIONSHIP IN ('KNG Officer') THEN 1
		 WHEN nr.RELATIONSHIP IN ('Father') THEN 2
		 WHEN nr.RELATIONSHIP IN ('Son') THEN 3 
		 WHEN nr.RELATIONSHIP IN ('Daughter') THEN 4
		 WHEN nr.RELATIONSHIP IN ('Mother') THEN 5
		 WHEN nr.RELATIONSHIP IN ('Wife') THEN 6
		 END AS ORDER_NO,
	nr.PAT_TYPE
	FROM medas.NEW_REGISTRATION nr 
	WHERE CAST(nr.EMPLOYEE_ID AS NUMBER(12,0)) IN (:mid)
	AND REGEXP_LIKE(nr.EMPLOYEE_ID, '^[0-9]+$') 
	AND REGEXP_LIKE(nr.EMIRATES_ID, '^[0-9]+$')
	)
-- --------------------------------------------------------------------
UNION
-- --------------------------------------------------------------------
	(
	SELECT
	'' AS MEDICAL_RECORD_NO,
	v.NAME_E AS PATIENT_NAME_EN,
	v.NAME_A AS PATIENT_NAME_AR,
	v.MOBILE_NO AS MOBILE_NO,
	v.MILITARY_NO AS MILITARY_NO,
	v.CIVIL_ID_NO AS PAT_CIVIL_ID_NO,
	v.PRIMARY_ID AS EMP_CIVIL_ID_NO,
	v.GENDER AS GENDER,
	v.RELATION AS RELATIONSHIP,
	v.DESIGNATION AS DESIGNATION,
	CASE WHEN v.RELATION IN ('KNG Officer') THEN 1
		 WHEN v.RELATION  IN ('Father') THEN 2
		 WHEN v.RELATION IN ('child' ) AND v.GENDER IN ('Male') THEN 3 
		 WHEN v.RELATION IN ('child' ) AND v.GENDER IN ('Female') THEN 4
		 WHEN v.RELATION IN ('Mother') THEN 5
		 WHEN v.RELATION IN ('Wife') THEN 6
	END AS ORDER_NO,
	CASE WHEN v.DEPENDENT IN ('Y') THEN 'Dependent' ELSE 'Employee' END AS  PAT_TYPE
	FROM MEDAS.VW_HR_FAMILY v
	WHERE v.MILITARY_NO IN (:mid)
	AND v.CIVIL_ID_NO NOT IN (:civil_Id)
	)
) a
ORDER BY a.ORDER_NO ASC
