############################################################################
					# PORT NO:
server.port = 8080
############################################################################
					# SPRING SECURITY
spring.security.user.name= hello
spring.security.user.password=hello_world

#Keywords: prod,test,dev
sso.type=prod
sso.mid=1914
sso.mid.list=959636,959651
############################################################################
					# ORACLE DATABASE -> PRODUCTION 
					
spring.datasource.url=jdbc:oracle:thin:@kngsc19rac1-scan:1521/MEDRAC
spring.datasource.username=eclinic
spring.datasource.password=Kng2023
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.jpa.properties.hibernate.default_schema=ECLINIC
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.Oracle12cDialect
#spring.jpa.hibernate.ddl-auto=none
spring.datasource.hikari.data-source-properties.oracle.jdbc.fanEnabled=false
spring.datasource.hikari.data-source-properties.oracle.jdbc.enableDataAffinity=false
spring.datasource.hikari.data-source-properties.oracle.net.ns.SQLnetDef.TCP_CONNTIMEOUT_STR=10000


spring.thymeleaf.cache=false
spring.thymeleaf.mode=LEGACYHTML5

app.name=sss
default.mid=1914
############################################################################
					# LOGGING LEVEL
logging.level.org.springframework.security=info
############################################################################




